# Usar una imagen oficial y ligera de Python 3.12
FROM python:3.12-slim

# Evita que Python escriba archivos .pyc en el disco
ENV PYTHONDONTWRITEBYTECODE=1
# Evita que Python haga buffer en los logs, para verlos en tiempo real en Docker
ENV PYTHONUNBUFFERED=1

# Crear y movernos a la carpeta de trabajo
WORKDIR /app

# Copiar primero el archivo de requerimientos (Optimiza el caché de Docker)
COPY requirements.txt .

# Instalar las dependencias (FastAPI, Uvicorn, SQLAlchemy, psycopg2, etc.)
RUN pip install --no-cache-dir -r requirements.txt

# Copiar todo el código de tu API al contenedor
COPY . .

# Exponer el puerto en el que correrá Uvicorn
EXPOSE 8000

# Comando para iniciar el servidor de FastAPI
# Según tu estructura, main.py está dentro de la carpeta 'app'
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]